"""allow document url to be null

Revision ID: 10d5b93b0023
Revises: fa6a0fa6854b
Create Date: 2022-04-06 10:11:04.119153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10d5b93b0023'
down_revision = 'fa6a0fa6854b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document', 'document_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document', 'document_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
