"""removed foreighker reference from lab table

Revision ID: de0b38428b32
Revises: 4b9d4f5a8348
Create Date: 2022-04-04 10:24:24.434869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de0b38428b32'
down_revision = '4b9d4f5a8348'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('lab_created_by_fkey', 'lab', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('lab_created_by_fkey', 'lab', 'users', ['created_by'], ['id'], ondelete='SET DEFAULT')
    # ### end Alembic commands ###
